import asyncio
import aiohttp
from Bots.Summary.BotWithServer.Helpers.tokenBot import FastApi_URL


async def async_send_request_to_fastapi(data, url):
    async with aiohttp.ClientSession(trust_env=True) as session:
        async with session.post(f"{FastApi_URL}/{url}", json=data) as response:
            # Проигнорируем ответ сервера
            pass


async def async_send_request(data, url):
    await async_send_request_to_fastapi(data, url)


def process_request(data, url):
    asyncio.run(async_send_request(data, url))


def check_ai_marker(original_string):
    return "Generated by dataminds" in original_string or "[club225246870|@club225246870" in original_string or "Generate by dataminds" in original_string


def make_perfect_answer(summary_answer, select_messages_count):
    answer = f"""Результат суммаризации {select_messages_count} сообщений:

{summary_answer}

Generated by dataminds 
    """
    return answer
