import asyncio
import json
import logging
import os

import pika
from aiogram import Bot, Dispatcher, types
from pydantic import BaseModel

from token_bot import TOKEN

QUEUE_NAME = "output_queue_TG"
EXCHANGE_NAME = "output_exchange"

logging.basicConfig(level=logging.INFO)

bot = Bot(token=TOKEN)
dp = Dispatcher(bot)


async def process_out(data):
    summary_out = data['text_summary']
    chat_id = data['chat_id']
    summary_messages_count = data['select_messages_count']
    message_text = make_perfect_answer(summary_out, summary_messages_count)
    message = await bot.send_message(chat_id, message_text)


def make_perfect_answer(summary_answer, select_messages_count):
    answer = f"""Результат суммаризации {select_messages_count} сообщений:

{summary_answer}

Generated by dataminds @sirius_summary_bot 
    """
    return answer


def callback(ch, method, properties, body):
    print(f" [x] {method.routing_key}:{body}")

    try:
        data = json.loads(body.decode())
        asyncio.run(process_out(data))

        ch.basic_ack(delivery_tag=method.delivery_tag)
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == "__main__":
    print("Bot started")
    amqp_url = os.environ['AMQP_URL']
    url_params = pika.URLParameters(amqp_url)
    url_params.heartbeat = 0
    connection = pika.BlockingConnection(url_params)

    # # connect to rabbitmq
    # connection = pika.BlockingConnection(
    #     pika.ConnectionParameters(host='rabbit_mq')
    # )
    channel = connection.channel()

    channel.exchange_declare(exchange=EXCHANGE_NAME, exchange_type='direct')

    result = channel.queue_declare(queue=QUEUE_NAME)

    severity = "tg_bot"

    channel.queue_bind(
            exchange=EXCHANGE_NAME, queue=QUEUE_NAME, routing_key=severity)

    channel.basic_qos(prefetch_count=1)

    # define the queue consumption

    channel.basic_consume(
        queue=QUEUE_NAME, on_message_callback=callback, auto_ack=False)

    print("Waiting to consume")

    # start consuming
    channel.start_consuming()


