version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672

  transmitter:
    build: rabbitMQ
    container_name: transmitter
    depends_on:
      - rabbitmq
    volumes:
      - ./rabbitMQ:/rabbitMQ

  app1:
    build: app
    container_name: app1
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 85 --reload"
    depends_on:
      - rabbitmq
      - transmitter
    ports:
      - 8005:85
    volumes:
      - ./app:/app

  app2:
    build: app
    container_name: app2
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 86 --reload"
    depends_on:
      - rabbitmq
      - transmitter
    ports:
      - 8006:86
    volumes:
      - ./app:/app


  app3:
    build: app
    container_name: app3
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 87 --reload"
    depends_on:
      - rabbitmq
      - transmitter
    ports:
      - 8007:87
    volumes:
      - ./app:/app

  vk_bot:
    build: vk_bot_output
    container_name: vk_bot
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./vk_bot_output:/vk_bot_output


  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - 8001:81
      - 8002:82
      - 8003:83
      - 8004:84
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

