def make_perfect_answer(summary_answer, select_messages_count):
    answer = f"""Результат суммаризации {select_messages_count} сообщений:

{summary_answer}

Generated by dataminds 
    """
    return answer